### PR TITLE
Fixed wrong SELECT and SHOW queries detection

### PR DESCRIPTION
**Pull request by mkreckovic**
Fixed wrong SELECT and SHOW queries detection due to leading tabs and spaces.

### CODE REVIEW

**Comment by pavelevap** [comment]
Good catch! For example this [query](https://github.com/WordPress/WordPress/blob/81668f8312d2c082aeff555012a3f00f71c1e202/wp-includes/comment.php#L378) from WP core is also affected.

Originally I thought that this is handled by WordPress by default, but it is done later :-( VersionPress is using custom method `query()` before using `__wp_query()` based on original function which handles queries with [strip_invalid_text_from_query()](https://developer.wordpress.org/reference/classes/wpdb/strip_invalid_text_from_query/) method. Maybe we could take some more inspiration from it, they are using `ltrim()` and also `DESCRIBE`, `DESC` and `EXPLAIN` queries could be ignored (not very frequent).

PR works for me, thank you @mkreckovic!

**Comment by candrews** [comment]
@borekb can you please take a look and perhaps merge this one?

**Comment by borekb** [comment]
It looks good to me, sorry for not getting to this earlier. Just to confirm, @candrews, you find the code correct, right?

**Comment by borekb** [comment]
Thanks for confirming. I'm going to merge the PR then – props to @mkreckovic!

**Pull request merged**
