### PR TITLE
Run tests in Travis

### PR DESCRIPTION
**Pull request by candrews**
Have Travis run all tests:
  - npm run lint:markdown
  - npm run build-images
  - npm run tests:full
  - ( cd plugins/versionpress && ./vendor/bin/phpcs --standard=ruleset.xml )

With this improvement, tests are automatically run so no one has to manually do so. Tests are also run for all branches and PRs allowing for test passage to be a quality gate.

### CODE REVIEW

**Comment by candrews** [comment]
Note that tests currently fail; #1376 #1379 #1380 all work towards making these tests pass.

**Comment by borekb** [comment]
This is awesome ❤️!

I'm inclined to merge this before the tests pass, do you agree?

**Comment by candrews** [comment]
Absolutely!

**Comment by borekb** [comment]
I wonder if it's useful to run `build-images` on Travis, what do you think @candrews?

**Comment by candrews** [comment]
> I wonder if it's useful to run `build-images` on Travis

I think it is.

If Travis doesn't build the images, then Travis can't test changes to the images. For example, if you modify a Dockerfile, and Travis isn't building images, then Travis won't be able to run tests with that change in place. This means docker changes can only be tested locally or after the image is pushed.

**Comment by borekb** [comment]
👍, you're right. It's a bit wasteful most of the time but we could add something like [this](https://stackoverflow.com/questions/47174711/perform-docker-build-only-if-dockerfile-is-changed) in the future.

**Pull request merged**
