### PR TITLE
Unsaved featured image test fix

### LINKED ISSUE #957: Failing turningUnsavedPostWithFeaturedImageIntoDraftSavesTheFeaturedImage test
This test fails when run from Selenium.

### PR DESCRIPTION
**Pull request by octopuss**
Resolves #957.

Reviewers:

- [ ] @JanVoracek

### CODE REVIEW

**Comment by JanVoracek** [comment]
Can you please add some quick summary (especially a note about new ignore rule)?

**Comment by octopuss** [comment]
I am a little bit upset with this pull requests. My results from yesterday's work are no longer valid. Sometimes Selenium tests work sometimes not. They got stuck in saving draft of post and the Firefox browser hangs, post url is not computed and no XHR requests are send to server. Also the ignoring of `*user-settings-time` was false positive. So what should we do ? The tested functionality works, but the tests are fragile (obviously caused by Selenium).

**Comment by octopuss** [comment]
Closing this PR, because changes implemented in it have no effect on resolving underlying issue.

**Comment by borekb** [comment]
It's not even clear what the underlying issue was, I was able to run the test just fine.

**Pull request closed without merging**
