### PR TITLE
Refactor of BulkActionPanel component

### LINKED ISSUE #1087: Use simple and clear React.js components
This issue is part of a frontend code review, see #1083.

Most components in the front ende codebase don’t do one thing, but several at once. This is not a good technique to follow. Because of this any future changes or improvements are extremely hard and a chance to make a mistake is much higher.

For example, the [CommitsTable](https://github.com/versionpress/versionpress/blob/master/frontend/src/Commits/CommitsTable.react.tsx) component is a very large one. The component can be very hard to follow and its formating style can make the component unreadable. 
The component can be split into smaller ones to improve its readability and clarity. The component even uses [CommitsTableNote](https://github.com/versionpress/versionpress/blob/master/frontend/src/Commits/CommitsTableNote.react.tsx) component, which is much easier to follow and does just a one thing.

### PR DESCRIPTION
**Pull request by Ishirak**
Resolves (partialy) #1087.

Few notes:
- Directory structure – as we agreed on – will be implemented after all of the components are refactored.

Reviewers:

- [x] @JanVoracek
- [x] @vasek17

### CODE REVIEW

**Comment by borekb** [comment]
> I don't believe that its solution should be handled by one huge PR. Therefore I opened this PR, which will be continuously updated to resolve this issue.

So is this going to be a single large PR (though created over time) or multiple smaller PRs? It's not clear from the description.

**Comment by Ishirak** [comment]
Sorry, my bad,  this going to be a single large PR (though created over time).

**Comment by Ishirak** [comment]
But if anyone has in mind a different aproach, I'm open to suggestions.

**Comment by borekb** [comment]
An alternative would be to create multiple smaller PRs against a single issue, as we discussed offline. The main benefit would be that smaller PRs could be merged into master sooner. But if @vasek17 doesn't depend on any of this work, single PR is fine.

**Comment by Ishirak** [comment]
I've tried this alternative before I posted mine, but since it's a single issue I only have a single branch to work with. After I'd create a PR, the PR has to be reviewed and I can't work on another refactoring in the branch because it'd violate the PR with refactoring which the PR is not part of. One possible solution could be divide the issue into two branches – refactoring of codebase can be parallel – but I don't like it that much. 

Maybe I'm missing some elementary GitHub workflow and there exists an easy fix which I'm not familiar with. If so, please enlighten me.

**Comment by Ishirak** [comment]
After internal discussion we are going for an alternative involving multiple smaller PRs. Thanks to @borekb for his insight on this issue.

**Comment by Ishirak** [comment]
Edited PR's description.

**Pull request merged**
