### PR TITLE
Bugs detected while creating WPML plugin definition files

### PR DESCRIPTION
**Pull request by mkreckovic**
I can explain every commit if needed.

### CODE REVIEW

**Comment by borekb** [comment]
Hi @mkreckovic, thanks for the PR, it looks good to me overall. Two commits that will require more attention (cc @JanVoracek) are:

- `TableSchemaStorage#getSchema` no longer throwing an exception https://github.com/versionpress/versionpress/pull/1317/commits/46e2669533478af3dc8cb8c4bbb2cd07ba7c0f5f
- Working with paths of all plugins, not just the active ones https://github.com/versionpress/versionpress/pull/1317/commits/6ce8409821bc163e57aa2e3c097e0089b13bacd7

**Comment by pavelevap** [comment]
Commit https://github.com/versionpress/versionpress/pull/1317/commits/344e1c100c970f0d7a8a071311ec3d3b8e9517fe probably fixes issue https://github.com/versionpress/versionpress/issues/1304.

**Comment by pavelevap** [comment]
Hi @mkreckovic,

commit https://github.com/versionpress/versionpress/pull/1317/commits/44b5474b851e360f5a70b72b716bba14fb9d91a1 is related to following queries?

`INSERT INTO wp_term_relationships ( object_id, term_taxonomy_id ) VALUES ( 1, 2 ),( 2, 2 )`

**Comment by borekb** [comment]
Copying relevant bits from [conversation on Gitter](https://gitter.im/versionpress/plugin-dev?at=5a82c05f8c71e5e01d8c13c3):

---

Marko Krečković @mkreckovic Feb 13 11:39
Hi @borekb ... regarding `TableSchemaStorage#getSchema` no longer throwing an exception, we have situation with divi builder plugin where tables for AB testing from divi plugin are not created when activated, but later when plugin needs them. So when we clone that repository and do `apply-changes` we get error because that tables are in schema file but they don't exists. I think that this change does not impair the functioning of the VP, and allows the plugins that create the tables later during usage, to work properly and don't throw exception.

Marko Krečković @mkreckovic Feb 13 12:09
Also we have situation when VP needs to know table schema before plugin is activated, because plugin activation populates some tables (WPML plugin). Because of that we changed `getPathsForActivePlugins` with `getPathsForPlugins`

**Comment by mkreckovic** [comment]
Yes @pavelevap , that's the query. `insert_id` holds the ID of last inseted row, so firstId will hold wrong value if we have query like that.

**Comment by pavelevap** [comment]
Great, so commit https://github.com/versionpress/versionpress/commit/44b5474b851e360f5a70b72b716bba14fb9d91a1 probably fixes related issue #1303, I will try to test your suggested fix.

**Comment by borekb** [comment]
@mkreckovic: as @pavelevap is reviewing the changes, it would be better to have them in separate PRs. Do you think you could re-submit as such? Sorry to bother you..

**Comment by borekb** [comment]
@mkreckovic Thanks for splitting this PR into separate ones. For reference, they are:

- Fix for plugins that create some tables later, not while activating #1320
- Fixed gitattributes duplicated entry on merge driver install #1321
- Fixed Windows escape shell args problem after Windows update #1322
- Return paths for all plugins not only active #1323
- Fixed wrong SELECT and SHOW queries detection #1324
- Fixed regex not including multiline strings while serializing #1325
- Added support for nested shortcodes #1326
- Fixed gitignore template to include plugin definitions #1327

@pavelevap, could you please do the first round of reviews on those PRs and ask @JanVoracek for assistance where needed? Thanks!

@mkreckovic Do you think we can close this PR? If everything has been transferred to the new PRs, feel free to do so.

**Comment by pavelevap** [comment]
I am going through separate PRs and testing them, but one commit from this PR is missing: https://github.com/versionpress/versionpress/pull/1317/commits/44b5474b851e360f5a70b72b716bba14fb9d91a1

I tested it before and it did not fix my issue with multiple entities for `INSERT` query.

@mkreckovic: This commit is no longer relevant or only misses its own PR?

**Comment by mkreckovic** [comment]
@pavelevap I reverted this commit because the problem is more complicated than I originally thought. When we have INSERT ... VALUES, WordPress really returns ID of the first inserted record for the firsId value, but if we have sometnig like VALUES (1, 'First'), (2, 'Second'), (3, 'Third') where 1, 2, and 3 are primary key field, then firstId returns last inserted record.

**Pull request closed without merging**
