### PR TITLE
Fix handling of values serialized multiple times

### LINKED ISSUE #1430: Double serialized value not serialized/deserialized correctly
I haven't yet been able to come up with shorter/simpler reproduction steps or a unit test. If someone does, please let me know - I'll keep working on it as well.

The problem can be reproduced by:
* Start with a VersionPress enabled Wordpress instance
* Install this plugin: https://wordpress.org/plugins/miniorange-saml-20-single-sign-on/
* In the wp-admin configuration for the plugin, set the x509 certificate to:
```
-----BEGIN CERTIFICATE-----
 MIIDnDCCAoSgAwIBAgIGAV2hzwAUMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYDVQQG
 EwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNj
 bzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMM
 Bmlzb2JhcjEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTAeFw0xNzA4MDIw
 NzE3MDRaFw0yNzA4MDIwNzE4MDNaMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
 Q2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0
 YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMMBmlzb2JhcjEcMBoGCSqG
 SIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
 AQoCggEBAJqzbApk1LTFnGF9E3OvS9fZkcRbHoiLVHyqnE5+ZIUsL3qBwgXbLlg1
 aiV3y5QCpv/SoDYNTkmG8Af5PC+qEFDqA1UnqDs3epJtK/SLLdRHNTJjesLXtgWL
 8YxcVh0FQkDUBUmOomEfokGU1oda+jjxYcee/zF7IUcETenWRmM5RXPvMxOVeSsq
 6ecc1z84gYiuD2qUR/WpZsA3A83K1O+kGhM56qkjlb9X1yco9vavw0NI+m70pSri
 VhcETrIZZpT1I4G3DRPAnStnoLFyp44WGPd8S4G3dSjClA4+cdTphKZL5nKin02F
 NGNB3sv+ubmsmsHUnTzkyr18iXKRbxMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
 CQW2NW9GjtkcZRImC+l9hSlDZ5NYvgjGE67arPdrbS1EDjmpOdz7E7yLEU6mpzsO
 xMsi5kta9rQhsOdbydz6swkkUxrhSm7lBbttkggHULN1dfhLMUmbBDCZ9cmfRZCo
 D0dW+bHjH4aDd3X1uguoGjoxTMaR3EM5z663rA3ogjRTbsdag4sjlpoVah40y0vi
 tVl4j/Uxn/VzzG1yGmPffrv8AWG4Zll9ZjIowbE9MnHdcMgj6sPBYJ7J1iVwlRMj
 9F8SeUPTzQhnh/40TH3KNVU6QSb5J1W4gCrRwxQ0HDlCZOAZyL5JJoIlGTqCbF5b
 AcPvBc/ggs5jNB6jaqLJ/A==
 -----END CERTIFICATE-----
```
* `wp option get saml_x509_certificate` The output correctly returns:
```
a:1:{i:0;s:1334:"-----BEGIN CERTIFICATE-----
MIIDnDCCAoSgAwIBAgIGAV2hzwAUMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYDVQQG
EwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNj
bzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMM
Bmlzb2JhcjEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTAeFw0xNzA4MDIw
NzE3MDRaFw0yNzA4MDIwNzE4MDNaMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
Q2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0
YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMMBmlzb2JhcjEcMBoGCSqG
SIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAJqzbApk1LTFnGF9E3OvS9fZkcRbHoiLVHyqnE5+ZIUsL3qBwgXbLlg1
aiV3y5QCpv/SoDYNTkmG8Af5PC+qEFDqA1UnqDs3epJtK/SLLdRHNTJjesLXtgWL
8YxcVh0FQkDUBUmOomEfokGU1oda+jjxYcee/zF7IUcETenWRmM5RXPvMxOVeSsq
6ecc1z84gYiuD2qUR/WpZsA3A83K1O+kGhM56qkjlb9X1yco9vavw0NI+m70pSri
VhcETrIZZpT1I4G3DRPAnStnoLFyp44WGPd8S4G3dSjClA4+cdTphKZL5nKin02F
NGNB3sv+ubmsmsHUnTzkyr18iXKRbxMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
CQW2NW9GjtkcZRImC+l9hSlDZ5NYvgjGE67arPdrbS1EDjmpOdz7E7yLEU6mpzsO
xMsi5kta9rQhsOdbydz6swkkUxrhSm7lBbttkggHULN1dfhLMUmbBDCZ9cmfRZCo
D0dW+bHjH4aDd3X1uguoGjoxTMaR3EM5z663rA3ogjRTbsdag4sjlpoVah40y0vi
tVl4j/Uxn/VzzG1yGmPffrv8AWG4Zll9ZjIowbE9MnHdcMgj6sPBYJ7J1iVwlRMj
9F8SeUPTzQhnh/40TH3KNVU6QSb5J1W4gCrRwxQ0HDlCZOAZyL5JJoIlGTqCbF5b
AcPvBc/ggs5jNB6jaqLJ/A==
-----END CERTIFICATE-----";}
```
* Run `wp vp apply-changes`
*  `wp option get saml_x509_certificate` The output is now incorrect:
```
<<<serialized>>> <<<serialized>>> <array>
```

Both before and after running `wp vp apply-changes`, `wp-content/vpdb/options/sa/saml_x509_certificate.ini` has not changed; the file contents are:
```
[saml_x509_certificate]
option_value = <<<serialized>>> <<<serialized>>> <array>
option_value[0] = "-----BEGIN CERTIFICATE-----
MIIDnDCCAoSgAwIBAgIGAV2hzwAUMA0GCSqGSIb3DQEBCwUAMIGOMQswCQYDVQQG
EwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNj
bzENMAsGA1UECgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMM
Bmlzb2JhcjEcMBoGCSqGSIb3DQEJARYNaW5mb0Bva3RhLmNvbTAeFw0xNzA4MDIw
NzE3MDRaFw0yNzA4MDIwNzE4MDNaMIGOMQswCQYDVQQGEwJVUzETMBEGA1UECAwK
Q2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0
YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxDzANBgNVBAMMBmlzb2JhcjEcMBoGCSqG
SIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
AQoCggEBAJqzbApk1LTFnGF9E3OvS9fZkcRbHoiLVHyqnE5+ZIUsL3qBwgXbLlg1
aiV3y5QCpv/SoDYNTkmG8Af5PC+qEFDqA1UnqDs3epJtK/SLLdRHNTJjesLXtgWL
8YxcVh0FQkDUBUmOomEfokGU1oda+jjxYcee/zF7IUcETenWRmM5RXPvMxOVeSsq
6ecc1z84gYiuD2qUR/WpZsA3A83K1O+kGhM56qkjlb9X1yco9vavw0NI+m70pSri
VhcETrIZZpT1I4G3DRPAnStnoLFyp44WGPd8S4G3dSjClA4+cdTphKZL5nKin02F
NGNB3sv+ubmsmsHUnTzkyr18iXKRbxMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEA
CQW2NW9GjtkcZRImC+l9hSlDZ5NYvgjGE67arPdrbS1EDjmpOdz7E7yLEU6mpzsO
xMsi5kta9rQhsOdbydz6swkkUxrhSm7lBbttkggHULN1dfhLMUmbBDCZ9cmfRZCo
D0dW+bHjH4aDd3X1uguoGjoxTMaR3EM5z663rA3ogjRTbsdag4sjlpoVah40y0vi
tVl4j/Uxn/VzzG1yGmPffrv8AWG4Zll9ZjIowbE9MnHdcMgj6sPBYJ7J1iVwlRMj
9F8SeUPTzQhnh/40TH3KNVU6QSb5J1W4gCrRwxQ0HDlCZOAZyL5JJoIlGTqCbF5b
AcPvBc/ggs5jNB6jaqLJ/A==
-----END CERTIFICATE-----"
autoload = "yes"
```

### PR DESCRIPTION
**Pull request by candrews**
Resolves #1430 

Test cases have been described by @pavelevap in https://github.com/versionpress/versionpress/issues/1430#issuecomment-488575299, this PR adds them to tests and implements a fix.

Double serialized values like `serialize(serialize('some string'))` are now handled correctly.

### CODE REVIEW

**Comment by pavelevap** [comment]
Note: There were strange errors in Travis build, but after I restarted this build, tests are passing now.
Maybe I could only trigger new build to preserve this error for future, but it is too late.
It seems to me, that this PR fixes all missing issues mentioned in issue #1430.

**Comment by pavelevap** [comment]
Hmm, strange Travis error is back for `CommentsSynchronizerTest`: https://travis-ci.org/versionpress/versionpress/builds/527328049#L1649 (different message, but same tests).

**Comment by candrews** [comment]
> Hmm, strange Travis error is back for `CommentsSynchronizerTest`: https://travis-ci.org/versionpress/versionpress/builds/527328049#L1649 (different message, but same tests).

The error seems to be:
`Error: Failed to get url 'https://wordpress.org/wordpress-4.9.tar.gz': cURL error 28: Operation timed out after 10001 milliseconds with 0 out of 0 bytes received.`

I suspect re-running the test will result in a pass. I bet the issue was a temporary problem in Travis's networking.

**Comment by pavelevap** [comment]
Maybe we should move new tests next to related tests (`serializedArrayInSerializedArray`, `serializedStringInSerializedArray`) and use similar naming and variables to group them visually? But it is probably subjective matter and not a big deal.

**Comment by candrews** [comment]
> Maybe we should move new tests next to related tests (`serializedArrayInSerializedArray`, `serializedStringInSerializedArray`) and use similar naming and variables to group them visually? But it is probably subjective matter and not a big deal.

I have updated this PR accordingly.

**Comment by borekb** [comment]
Thanks for this, @candrews. I've pushed small formatting updates and am going to merge this.

As a reminder, please try to avoid force pushes on this project :)

**Pull request merged**
