### PR TITLE
Feature/1332 use mk docs for docs.versionpress.net

### LINKED ISSUE #1332: Use MkDocs for docs.versionpress.net
[Our docs](https://docs.versionpress.net/en) are currently powered by [versionpress/docs-site](https://github.com/versionpress/docs-site), a small Node.js app that serves a bunch of Markdown files – currently the contents of [`/docs/content`](https://github.com/versionpress/versionpress/tree/2071052ad33a782e96ca206ccca6891e52bc614f/docs/content) folder in this repo. The idea was that we'd be able to switch versions of the documentation and language versions but the reality is that these features are not used and static site generation would be much simpler.

Specifically, [MkDocs](http://www.mkdocs.org/) + [mkdocs-material](https://squidfunk.github.io/mkdocs-material/) is a nice combo that we already use for our [".com" docs](https://docs.versionpress.com/) and would also provide all we really need for ".net" docs:

- Markdown source files
- Search
- Navigation: menu & prev/next
- Design options

If someone wanted to take this, it would be great. What should happen as part of the PR:

- [ ] Update the Markdown files and their structure for MkDocs
- [ ] Move the release notes to GitHub releases and/or `CHANGELOG.md`
- [ ] Ideally keep the design. I quite like the distinct, although relatively old-school [looks of our docs](https://user-images.githubusercontent.com/101152/40269203-2f5d4c2a-5b7b-11e8-9ea0-5ca338689e0c.png).
- [ ] Update README / deployment instructions

Related: https://github.com/versionpress/docs-site/issues/92

### PR DESCRIPTION
**Pull request by lisaross**
Resolves #1332 
(I think)

Lots of files and configurations changed but I've done my best to document how and what was done.

**Some highlights:**
- moved files into structure that is more audience specific (ie. developer vs user, as well as making more multilang friendly when the time comes)
- mkdocs runs it all, with material theme bringing features like search
- theme uses material for function but modded to create similar look/feel to existing .net 
- switched out markdown note engine from html to admonition and refactored documentation
- functionality for theme override in place with instructions in readme
- tested docs to ensure links aren't broken

**Still to do**
- not sure how you want to deploy - left it in the README for you to decide and we can update the docs as needed
- mkdocs doesn't have a great system in place for redirection, in the event that we want to point someone to the new link should they land on an old one. Depending on how we deploy, we can either use server side redirection using .htaccess for example, or we can create files in old location that manually redirect to new. I would say we should open a new issue for redirection and go from there though.

**Some notes**
- this is actually my first pull request ever, so please be kind if I've screwed something up. 💃 
- if you have any questions about how something works please let me know
- realized after the fact that this should have been tagged 'improvement' rather than 'feature' I think. Sorry.
- wasn't sure if you have any automated tests in place for this - if so, please point me in the right direction. If not, I'd love to work with someone to see about making them.
- don't hesitate to punt it back to me if it's a disaster. I only just started using git, for example, so if my commits aren't to standard I'd love coaching on that (or anything, for that matter)

---

@borekb 🏁 notes:

This is an awesome PR and a nice refresh of our docs, thanks @lisaross! Highlights from my point of view are:

- Static site hosted on GitHub Pages instead of a [custom Node.js app](https://github.com/versionpress/docs-site) that was bothersome to run and maintain.
- Developer documentation is now part of the docs as well.
- Much easier contributions via GitHub pull requests – there's an edit button on each page.
- We use a standard documentation system, [MkDocs](https://www.mkdocs.org/), instead of a custom one.

New site:

image

Original site:

image

### CODE REVIEW

**Comment by borekb** [comment]
Wow @lisaross this is extremely impressive, especially for a first PR! I'll be able to take a closer look later this week but it looks very good at first sight, and I appreciate you taking time to provide a great PR description.

Congratulations, this is an awesome contribution, and thank you!

**Comment by borekb** [comment]
Hi @lisaross, I'm starting to look at this PR now, will commit some changes directly if you don't mind. If there's things to discuss more, I'll post here.

**Comment by borekb** [comment]
For reference, this is how the docs look at the moment:

image

More complex page:

image

**Comment by borekb** [comment]
I'll call it a night but made some progress:

In the last few commits, I've mostly simplified the README which I believe can be much shorter now that we use a standard documentation system. @lisaross, what do you think, is the shorter version enough?

Another major thing is Docker for running and building the docs – the main motivation is that Python is not always easy to install in the right version or on all systems. With Docker, building the documentation is just `npm run build`, live-previewing edits is `npm run start`.

Some other notes so far:

- I liked that the developer docs moved from plain Markdown files to public docs 🚀.
- Link to GitHub from docs is cool, being able to edit docs directly will be useful.
- `Dev-Setup.md` (now `setup.md`) is heavily changing in Dev setup updates – spring 2018 #1329 but that's not a problem, I'll merge it later.
- Redirections: I wouldn't worry about them too much, VersionPress is a Developer Preview and the search feature is powerful enough, IMO. But if we can find a simple system for redirection, of course that would be better.
- _"switched out markdown note engine from html to admonition and refactored documentation"_ 👍
- `[TODO]` markers are no longer supported, I've removed them from README

TODO as I currently see it:

- [x] Review `docs/README.md`, some info is outdated
- [ ] Set up GitHub Pages as a deployment mechanism
- [ ] Theme:
    - [ ] I'd prefer things like JavaScript or `vp_theme` not be in the `content` directory
    - [ ] Customize footer (we have the black one on .com)
    - [ ] Header is transparent, probably shouldn't be
    - [ ] Code blocks are rendered strangely ([example](https://user-images.githubusercontent.com/101152/40810398-ebea886a-652d-11e8-8f28-720836a5509e.png))

**Comment by borekb** [comment]
About **deployment**:

This is an ideal workflow, IMO:

1. A PR updating some files in `docs/content` is opened, reviewed and merged.
    - Inside the PR, we could introduce docs-specific checks like [linting the Markdown documents](https://github.com/markdownlint/markdownlint) in the future.
    - Ideally, _only_ docs-specific checks would be run.
2. On merge, CI builds the docs: basically `cd docs && npm run build`. Again, some CI smartness would be welcome, for example, there's no need to run an hour-long integration tests if only docs were updated.
3. On successful docs build, the contents of `docs/site` (current output folder) would be pushed to a repo like `versionpress/docs.versionpress.net`. I'd prefer that over the `gh-pages` branch and setting up a GitHub Pages site update would be trivial in that case.

I briefly looked at Travis CI that we already use for PHP code style checks but to be honest, I'm not sure how to achieve the above. @lisaross, do you have any experience with it? If not, I think it would be better to solve the deployment separately not to block this already very useful PR.

Notes from my brief Travis CI research:

- [This](https://gist.github.com/domenic/ec8b0fc8ab45f39403dd) is an interesting example of how to build and publish to GitHub Pages.
- ["Build Stages"](https://docs.travis-ci.com/user/build-stages/) might be a way to separate various jobs but not sure.
- Some discussion about Travis and monorepos with a specific tip here: https://github.com/travis-ci/travis-ci/issues/3540#issuecomment-330188464

For reference, these are [our current Travis CI checks](https://travis-ci.org/versionpress/versionpress).

**Comment by lisaross** [comment]
@borekb Amazing - thanks for taking so much time to explain above. I'll have a closer look this weekend, but so far: I LOVE the docker plan. I started toying with Docker myself a few weeks ago and definitely see the benefit of this direction.

**Comment by borekb** [comment]
Hi @lisaross, do you have any new code to push at the moment? I will be going through the PR shortly and am already aware of things that need fixing / updating, so I'd like to synchronize our work not to create many merge conflicts.

**Comment by lisaross** [comment]
Nope nothing yet @borekb - was going to have a look this afternoon :)

**Comment by borekb** [comment]
It's already afternoon here in GMT+1 so I'll go through it and hopefully, it will be less work for you by the time Earth gets a chance to rotate a bit :)

**Comment by borekb** [comment]
Some more progress:

- I've updated `mkdocs.yml` a bit, see [recent commits](https://github.com/versionpress/versionpress/pull/1334#commits-pushed-4226807) for details.
- d5add3a moved styling concerns (CSS, JS) from `content` to the separate `theme-mods` folder.

Some more things I noticed:

- [ ] Links should always end with `/`, for example, `http://localhost:8000/en/user/getting-started` should be `.../getting-started/` to avoid 302 redirect.
- [ ] Light header will require updates to other elements that currently not always have enough contrast. For example: <br><br>image
- [ ] I'd probably flatten the structure from `.../en/something` to just `.../something`, both in URLs and in directories. (Also, it's not correct that we currently have `content/index.md` outside of the `en` directory; that piece of content would be subject to localization as well). We're probably long ways off having fully localized documentation so all this `en` everywhere is just adding noise, IMO.

It's progressing nicely, overall, and I like working with MkDocs + material.

**Comment by borekb** [comment]
@lisaross I'm doing some more changes around structure and content, this _could_ be conflicting changes to your work so please hold on. I should be able to push in about an hour or two.

What is safe to work on are theme updates: some contrast issues with the header, etc.

**Comment by lisaross** [comment]
Got it. Today might be a write off anyway, but if so I’ll get the theme fixed up tomorrow. Loving all the work you’re doing.

**Comment by borekb** [comment]
8693393 is an important change to the docs structure that reverts back the move of most of the content to the `/user/` subfolder. I didn't notice this previously and that change unfortunately breaks all old URLs (some like https://docs.versionpress.net/en/getting-started/about-eap are used in many places, including VersionPress' UI). This also made me think about the scope of this PR but I'll post that separately.

I've also reviewed all of the links so that they work both when rendered by MkDocs and on GitHub. For this to be the case, one has to use relative links and a `.md` extension at the same time, for example, `[configuration](../getting-started/configuration.md)`.

**Comment by borekb** [comment]
The [past couple of commits](https://github.com/versionpress/versionpress/pull/1334#commits-pushed-65040bc) mostly resolve this TODO list:

- [x] Title Casing for developer docs
- [x] lower-case admonitions (`Tip` => `tip`; both work but lowercase is the "official" way to write them)
- [x] Fenced code blocks: sometimes, triple backtick is followed by space and some updates changed resulting HTML structure, e.g., `iis.md` in https://github.com/versionpress/versionpress/pull/1334/commits/4350046bb2de6b3bbbcef9bd7a63a896829e8c30
    - [x] Search for `-inline`, don't use it (doesn't render well on GitHub)
- [x] Remove "since:" tags
- [x] Review Markdown extensions
- [ ] favicon.ico is 15kB (even better would be to upload to GitHub CDN; I had some technical difficulties, see https://github.com/squidfunk/mkdocs-material/issues/789)

**Comment by borekb** [comment]
At this point, I'm pretty happy with the new docs. The system is really nice to work with, there are Edit buttons for easy content updates, the old URLs still work, the design is an interesting blend of material and our original look, etc. Good stuff.

The rest of the work should be mostly visual (transparent header, better contrast in some cases, customized footer) and technical (`content/img` -> CDN, incorrect URL for GitHub and Twitter icons in the footer). We're close.

**Comment by borekb** [comment]
@lisaross Thanks for the visual fixes in c4bae26, it's much better now.

I've also merged in `master` which now contains a major update of `dev-setup.md` from PR #1329.

This evening, I should find some time to look at this PR again, work on the smaller remaining issues and hopefully get it prepared for merge.

**Comment by lisaross** [comment]
Nice! I have to fix up the footer today and I think that’ll be a good commit to merge. Stay tuned :) if there’s anything else I can do please let me know. I’m super excited to have been able to help!
		
		

		Get Outlook for iOS
	




On Thu, Jun 7, 2018 at 8:53 AM -0400, "Borek Bernard" <notifications@github.com> wrote:












@lisaross Thanks for the visual fixes in c4bae26, it's much better now.


I've also merged in master which now contains a major update of dev-setup.md from PR #1329.


This evening, I should find some time to look at this PR again, work on the smaller remaining issues and hopefully get it prepared for merge.

**Comment by lisaross** [comment]
Gah! I just merged something into master without meaning to I think... please rewind if needed, @borekb

**Comment by borekb** [comment]
Yeah, everything is alright :) Actually, GitHub would prevent any accidental push to `master` so you'll safe.

**Comment by borekb** [comment]
> I was going to mod the whole footer file to make it look like .net, but realized that was probably enough and kept it simple.

Yep, I actually like the current footer very much – keeps the style of previous docs but is more useful / modern.

> Otherwise, I think the styling is ok for now? Or did I miss something?

Generally, I think it looks awesome, just the contrast of the search box is sometimes not great, e.g., on hover. Do you want to look into that? I could also experiment with it a bit.

**Comment by borekb** [comment]
I'm looking at the styles, for example, setting the `theme.palette.primary` value to a hex value doesn't seem to have any effect. Give me a few moments to review this, thanks.

**Comment by borekb** [comment]
I've done some slight visual fixes in 070f528, I'm happy with it now.

Still to-do (plan to do this tonight):

- [ ] logo.png is too small for mobile view with sidebar opened - it's pixelated. Plus, upload to CDN.
- [ ] Sort out favicon.
- [ ] Final review

**Comment by borekb** [comment]
Hi @lisaross, sorry for the delay, I think I'll find time today evening to have a look at the GitHub Pages deployment (just document the manual process in README) and then I'd be happy to merge this PR. Is that fine with you? Anything else you would like to look at? Thanks.

**Comment by lisaross** [comment]
oh my goodness, don't apologize! 😄Let's do it! I didn't get a chance to look at the search styles, but we can probably do a minor after the PR is merged, yes? Thanks for including me in this process btw. I love that I've been able to contribute.

**Comment by borekb** [comment]
Thanks. I'll probably write a quick blog post about the new docs and would like to credit you, do you have a Twitter profile or something that you'd prefer me to use? Your contribution has been awesome!

**Comment by lisaross** [comment]
WOW! THANKS! My twitter profile is @iamlisaross but I've updated my github profile to display info instead if that's easier/better. 👍 https://github.com/lisaross

**Comment by borekb** [comment]
🎉 the docs site is now updated and runs on GitHub Pages: https://docs.versionpress.net/

I'll make some final notes in this PR later tonight and merge.

**Pull request merged**
