### PR TITLE
Fixed uninstallation test

### LINKED ISSUE #886: Failing test completeUninstallationOfUnactivatedPluginRemovesAllFiles
Test fails only when run using `gulp run-tests`. It does not fail when run separately.
 ```
Fatal error: Class 'VersionPress\Database\WpdbMirrorBridge' not found in /Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/src/DI/DIContainer.php on line 85 Call Stack: 0.0018 406288 1. {main}() /Users/ivan/Work/Sites/vp01/wp-admin/plugins.php:0 0.4864 30509528 2. delete_plugins() /Users/ivan/Work/Sites/vp01/wp-admin/plugins.php:375 1.3687 31444064 3. set_site_transient() /Users/ivan/Work/Sites/vp01/wp-admin/includes/plugin.php:873 1.3688 31444344 4. update_site_option() /Users/ivan/Work/Sites/vp01/wp-includes/option.php:1650 1.3688 31444584 5. update_network_option() /Users/ivan/Work/Sites/vp01/wp-includes/option.php:1055 1.3690 31450128 6. update_option() /Users/ivan/Work/Sites/vp01/wp-includes/option.php:1431 1.3691 31459136 7. wpdb->update() /Users/ivan/Work/Sites/vp01/wp-includes/option.php:325 1.3691 31459408 8. VersionPress\DI\DIContainer->resolve() /Users/ivan/Work/Sites/vp01/wp-includes/wp-db.php:3276 1.3691 31459592 9. VersionPress\DI\DIContainer::VersionPress\DI\{closure}() /Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/src/DI/DIContainer.php:39 Fatal error: require(): Failed opening required '/Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/tracy/tracy/src/Tracy/templates/bluescreen.phtml' (include_path='/Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/phpunit/php-token-stream:/Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/phpunit/php-code-coverage:/Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/phpunit/phpunit-mock-objects:/Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/phpunit/phpunit:/Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/symfony/yaml:/Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/phpunit/phpunit-selenium:.:/Applications/MAMP/bin/php/php5.6.10/lib/php') in /Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/tracy/tracy/src/Tracy/BlueScreen.php on line 61 Call Stack: 0.0018 406288 1. {main}() /Users/ivan/Work/Sites/vp01/wp-admin/plugins.php:0 0.4864 30509528 2. delete_plugins() /Users/ivan/Work/Sites/vp01/wp-admin/plugins.php:375 1.3687 31444064 3. set_site_transient() /Users/ivan/Work/Sites/vp01/wp-admin/includes/plugin.php:873 1.3688 31444344 4. update_site_option() /Users/ivan/Work/Sites/vp01/wp-includes/option.php:1650 1.3688 31444584 5. update_network_option() /Users/ivan/Work/Sites/vp01/wp-includes/option.php:1055 1.3690 31450128 6. update_option() /Users/ivan/Work/Sites/vp01/wp-includes/option.php:1431 1.3691 31459136 7. wpdb->update() /Users/ivan/Work/Sites/vp01/wp-includes/option.php:325 1.3691 31459408 8. VersionPress\DI\DIContainer->resolve() /Users/ivan/Work/Sites/vp01/wp-includes/wp-db.php:3276 1.3691 31459592 9. VersionPress\DI\DIContainer::VersionPress\DI\{closure}() /Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/src/DI/DIContainer.php:39 1.3699 31455960 10. Tracy\Debugger::_shutdownHandler() /Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/tracy/tracy/src/Tracy/Debugger.php:0 1.3702 31467880 11. Tracy\Debugger::_exceptionHandler() /Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/tracy/tracy/src/Tracy/Debugger.php:377 1.3703 31469592 12. Tracy\BlueScreen->render() /Users/ivan/Work/Sites/vp01/wp-content/plugins/versionpress/vendor/tracy/tracy/src/Tracy/Debugger.php:423

```

### PR DESCRIPTION
**Pull request by borekb**
Resolves #886.

The fix is now ready. Expired session (commit https://github.com/versionpress/versionpress/pull/937/commits/48854785fbbe54c7ff44efcd1ca1539af824c683) was nonsense.

Reviewers:

- [x] @JanVoracek 
- [x] @octopuss

### CODE REVIEW

**Comment by borekb** [comment]
Expired session is weird, it must have been caused by something else. I'll need to look at this again.

**Comment by borekb** [comment]
FINALLY, I think we might have the root cause identified. The simplest code that can reproduce the issue is this:

```
public function setUp() {
    self::$wpAutomation->setUpSite();
    self::$wpAutomation->copyVersionPressFiles();
    self::$wpAutomation->initializeVersionPress();
}

/**
 * @test
 */
public function completeUninstallationOfUnactivatedPluginRemovesAllFiles() {

    $origFile = self::$testConfig->testSite->path . '/wp-includes/wp-db.php.original';

    self::$wpAutomation->uninstallVersionPress();
    $this->assertFileNotExists($origFile);

    self::$wpAutomation->copyVersionPressFiles();
    $this->assertFileNotExists($origFile);

    $this->url('wp-admin/plugins.php');
    $this->byCssSelector('#versionpress .delete a')->click();
    $this->byCssSelector('.wrap form:nth-of-type(1) input#submit')->click();

    $this->waitForElement('.plugins-php #message.updated');

    $this->assertFileNotExists(self::$testConfig->testSite->path . '/wp-includes/wp-db.php.original');
    $this->assertFileNotExists(self::$testConfig->testSite->path . '/wp-content/plugins/versionpress');
    $this->assertFileNotExists(self::$testConfig->testSite->path . '/.git');
}
```

It does the full site setup before the test and the test itself is basically the same, just the `_installVersionPress()` method has been inlined and an _file does not exist_ assert has been placed in the middle of it. **This assertion fails.**

As pointed out by @octopuss and @JanVoracek, the `.original` file is actually deleted but added by some mysterious process back. I've updated the shutdown handler with this logging code:

```
register_shutdown_function(function () {

    $logFile = "c:/temp/log.txt";
    file_put_contents($logFile, "\n\n-----------------\n" . date(DATE_RFC2822) . "\n", FILE_APPEND);
    if (function_exists('getallheaders')) {
        file_put_contents($logFile, print_r(getallheaders(), true), FILE_APPEND);
    } else {
        file_put_contents($logFile, "WP-CLI", FILE_APPEND);
    }

    if (!WpdbReplacer::isReplaced() && !defined('VP_DEACTIVATING')) {
        WpdbReplacer::replaceMethods();
    }
});
```

and the output is this:

```
-----------------
Mon, 18 Apr 2016 14:25:13 +0000
Array
(
    [Host] => localhost
    [User-Agent] => Mozilla/5.0 (Windows NT 10.0; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
    [Accept] => text/html, */*; q=0.01
    [Accept-Language] => en-US,en;q=0.5
    [Accept-Encoding] => gzip, deflate
    [X-Requested-With] => XMLHttpRequest
    [Referer] => http://localhost/vp01/wp-admin/
    [Cookie] => wordpress_2ecacd497f51810ab36d7091d57fe50b=admin%7C1461162306%7CJMG6pib4y1ql5u8bFsdFn4bhn5ra2aEFA4Y4kKgXCsN%7C9bb662baf81353b6e94e0b1491d160f03a5f2b7ae8a187ef897caf63c2f9e6dd; wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_2ecacd497f51810ab36d7091d57fe50b=admin%7C1461162306%7CJMG6pib4y1ql5u8bFsdFn4bhn5ra2aEFA4Y4kKgXCsN%7C0e4042e61244f1c8a7a187ad65a9352e79310f9dfb63e40b5f5c60101096d564; wp-settings-time-1=1460989506; PHPSESSID=lktj0fjt4fbvr6bqr4koa8ncu5
    [Connection] => keep-alive
)


-----------------
Mon, 18 Apr 2016 14:27:27 +0000
Array
(
    [Host] => localhost
    [User-Agent] => WordPress/4.4.2; http://localhost/vp01
    [Accept] => */*
    [Accept-Encoding] => deflate;q=1.0, compress;q=0.5, gzip;q=0.5
    [Content-Length] => 0
    [Content-Type] => application/x-www-form-urlencoded
)


(...some more HTTP requests here...)


-----------------
Mon, 18 Apr 2016 14:27:33 +0000
WP-CLI

-----------------
Mon, 18 Apr 2016 14:27:38 +0000
Array
(
    [Host] => localhost
    [User-Agent] => Mozilla/5.0 (Windows NT 10.0; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0
    [Accept] => text/html, */*; q=0.01
    [Accept-Language] => en-US,en;q=0.5
    [Accept-Encoding] => gzip, deflate
    [X-Requested-With] => XMLHttpRequest
    [Referer] => http://localhost/vp01/wp-admin/
    [Cookie] => wordpress_2ecacd497f51810ab36d7091d57fe50b=admin%7C1461162449%7CAcheMsui10xyd6WCuzBlx90MTs8xp80mHNSVNknpZLL%7C3daf94cd32a17c6a48c5ddd8b68c95415229d55dd5b6959edb683dadc3d96fa0; wordpress_test_cookie=WP+Cookie+check; wordpress_logged_in_2ecacd497f51810ab36d7091d57fe50b=admin%7C1461162449%7CAcheMsui10xyd6WCuzBlx90MTs8xp80mHNSVNknpZLL%7Cb96c67f6c559f9bf7f7192584be96851f7162c925f9800497742a83f1e137876; wp-settings-time-1=1460989650; PHPSESSID=gq12h2cee4g5ilub1sofjto551
    [Connection] => keep-alive
)
```

The problem is that for the test, the test runner starts the browser and **there is one additional request after VersionPress has been deactivated**. This causes the shutdown handler to create the `.original` file again when it shouldn't. The fix will now be relatively straightforward.

**Comment by borekb** [comment]
Ok the fix is ready for review.

**Comment by octopuss** [comment]
I've tested it and it works using `wp-cli` workers. I will try `selenium` workers as well.

**Pull request merged**
